ucsc-cgp/cloud-billing-report

.gitignore
Dockerfile
README.md
accounts.csv.example
cpanfile
docker-compose.yml
recipients.example
report_aws_spending

This PR formats AWS cost reports to address DataBiosphere/azul#1674:
> Here are my biggest cosmetic pain points:
> 
>     * tables aren't tabular so columns don't align and rows look jagged
> 
>     * Headings don't stick out enough
> 
>     * headings are closer to the preceding section and look more like "footings"
> 
>     * there should be anchor links from the top into the sub-reports for each account
This PR is larger than was originally anticipated for a couple of reasons:
* In order to publish this code publicly, hardcoded private information, such
as email addresses, AWS account names, and account numbers needed to be
removed from the script. To minimize the work needed to run the script once
the changes in this PR were implemented, the script was refactored to allow
specifying …

Reformat AWS cost reports

---

gcp/report_gcp_spending

Same round of changes as in the AWS report:
* Converted format to HTML
* Data now aligned in tables
* Added anchor links that lead to each account
* Added per-account diffs in summary table
* Larger headers
* Diffs of $0.00 are omitted entirely
* Negative diffs are bolded and highlighted in red
Among other things.

Convert GCP cost report to HTML (#4)

---

aws/.github/label.yml

Repo key needs to be configured in settings by an admin.

Add orange labeler (#9)

---

report.py

Noncompliant resources were incorrectly being filtered. Should only be reporting resources for the current day.
Ticket: #39

Noncompliant resources will only be reported for the current date

---

src/compliance_report.py
src/report_resource.py

There was a pagination bug when filtering the compliant resource tags. This has been fixed so the tags are correctly matched to their respective resource object.

Fix pagination issue when filtering tags of compliant resources

---

report.py

The Google BigQuery dataset takes time to populate with the previous day's billing data. This makes the report, which runs early in the morning, generally run on a partially complete dataset. To remedy this, have the Google report run 2 against billing data from 2 days back.

Moving the report date back one day

---

Dockerfile
report.py
requirements.txt
templates/gcp_report.html

This PR implements a couple of features to the GCP report that Benedict requested during a 10/Apr/2023 conversation:
1. A new "Details by service" section, which contains a table for each service, listing the costs by platform and in total.  Essentially, this is an inversion of the "Details by platform" section.
2. The existing "Details by platform" and new "Details by service" sections are [now] sorted in descending cost order, so that the tables and table rows with the highest monthly cost appear first.
I added links throughout, from the platform/service name to the appropriate "Details" table.
The alphabetical sorting of the summary "total" information at the beginning of the report has not changed.

Add inverted "Details" table, and sort in descending cost order

---

.github/workflows/docker-publish.yml

This PR updates the docker-publish action workflow to use `GITHUB_TOKEN`, as recommended here:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

Update action to use GITHUB_TOKEN

---

.github/workflows/docker-publish.yml

See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

Add permissions to docker-publish action

---

.github/workflows/docker-publish.yml

This PR reverts some experimental token changes to the previous code that uses a personal access token to push images to ghcr.io

Revert docker-publish token changes

---

report.py

This PR changes `report.py` as follows:
1. Read all of the AWS usage files that are specified in the manifest file, rather than only the first one as it does currently.   The usage information has been spread across multiple files in recent months, and the first file (of two) is currently empty. 
This bug may be responsible for the disappearance of the user information from the AWS report, and has probably caused inaccuracies in the report for months, perhaps longer. 
2. Properly handles costs attributed to a project with no name.

Process all usage files, handle None project

---

report.py

The existing code uses `s3.download_fileobj` to download the usage files from S3.  `download_fileobj` multithreads large downloads, but does not flush the downloaded file contents.  So, we must `flush` before we `open` the downloaded file to process it, because if we don't, the downloaded file will sometimes appear truncated and or contain holes.
This PR adds a `flush` in the appropriate location.

Fix usage file download bug

---

report.py

Recently, in the raw AWS data, rows which reflect EDP discounts (`LineItemType` of `EdpDiscount`) began to appear, which made our processing code fail because the said rows have a blank string as the "blended" cost, causing the decimal string conversion to throw. 
This change causes EDP discount-related rows to be ignored, similarly to how we currently treat credits and refunds.

Ignore "edp discount" rows

---

.github/workflows/docker-publish.yml

Increases the version of the github checkout action to `v3` to avoid a stale node dependency.

Bump actions/checkout version

---

.github/workflows/docker-publish.yml

https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token

Switch ghcr auth to GITHUB_TOKEN

---

.github/workflows/docker-publish.yml

https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token

Set permissions in action

---

Dockerfile
requirements.txt

The reporting image is experiencing an occasional failure due to what appears to be a DNS name lookup problem.  As part of the campaign to eliminate the issue, update the python image to 3.11.5 and the boto3 package to the latest version, just in case the bug is in that part of the stack.

Update python image to 3.11.5 and boto3 to latest

---

report.py

The project name in the google billing data is normalized so that all non-numeric chars are mapped to '-'.  Normalize the ID that we compute from the Terra workspaces data similarly.

Normalize terra project "name"

---

report.py
templates/gcp_report.html

Previously, the reporting script was aggregating cost data using the project name, which is not necessarily unique, and for Terra GCP projects, is formed by concatenating the Terra namespace, `--`, and the Terra project name.    Google limits project names to 30 chars, so the upshot is that for long namespaces, there's truncation, and multiple Terra projects were getting aggregated into one entry in the report.
This PR changes the script to aggregate on the GCP project ID, which is globally unique.  It also tweaks the output slightly.

Aggregate gcp report by project ID

---

report.py

A previously-unseen discount type began to appear in the AWS data, the lines for which the `blendedCost` value was empty, causing the reporting script to crash.  This PR changes the AWS report to only process lines in the data that correspond to a cost (lines with a `LineItemType` that ends with `Usage`, `Fee`, or `Tax`).

Only process lines in aws data that refer to a cost

---

report.py

In the GCP report, some projects were named "None", because some of the data that Google returned contained a null `project.name` field.  These results were interspersed with data that contained the correct `project.name` value.
The fix is to change the `reduce()` method (that aggregates values) to prefer a non-`None` value when it is reducing a list of strings.  This will cause the correct name to be displayed if Google returned any records that contained the correct project name for a given project id.

Fix "None" project names in GCP report 

---

report.py
requirements.txt
templates/gcp_report.html

This PR modifies the cloud reporting script to save AWS/GCP cost/usage information to an AWS S3 bucket, so that it can be used for analysis and billing purposes.  The script save the files for the specified platform every time it runs, unless the configuration file has not been properly updated (see below), in which case it operates as before.
AWS and GCP usage information is saved as CSV files, wherein each row represents a day of cost/usage for a particular project/account, and each CSV file represents a month of usage.  The current month's files are updated in place.  Terra account information is logged daily in a JSON file.  The following recursive `ls` output illustrates the structure of files (keys/objects) in the bucket:
```
bash-3.2$ aws s3 ls --recursive <bucket-name>
2024-10-30 …
```

Persist usage data

---

report.py

Make sure the archived S3 file objects use iso dates and date components in their names/paths.

Use iso dates in file names
